# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tyler's Blog
tagline:          'Security'
description:      'security stuff'
url:              https://tmart234.github.io
baseurl:          /

author:
  name:           'Tyler'
  url:            https://github.com/tmart234

paginate:         1
