# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hyde
tagline:          'Tyler'
description:      'security stuff'
url:              https://tmart234.github.io
baseurl:          /

author:
  name:           'Tyler'
  url:            https://github.com/tmart234

paginate:         5

# Custom vars
version:          2.1.0
