# Dependencies
markdown:         redcarpet
highlighter:      pygments

permalink: /:year-:month-:day-:title/
paginate: 5

# Setup
title:            Tyler's Blog
tagline:          'Security'
description:      'security stuff'
baseurl:           ''
url:              https://tmart234.github.io

author:
  name:           'Tyler'
  url:            https://github.com/tmart234


plugins:
  - jekyll-paginate