# Dependencies
markdown:         redcarpet
highlighter:      pygments

permalink: /:title/
paginate: 5

# Setup
title:            Let's Talk About MedSec
tagline:          'Security'
description:      'unadulterated hot takes on medical device cybersecurity'
baseurl:          ""
url:              https://tmart234.github.io

author:
  name:           'Tyler'
  url:            https://github.com/tmart234


plugins:
  - jekyll-paginate
